name: Buildozer
on: [push, pull_request]

jobs:

  android-debug:
    name: Android (debug)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: launcher
          #buildozer_version: stable
          buildozer_version: git+https://github.com/misl6/buildozer.git@feat/aab-support
          command: buildozer android release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: debug
          path: ${{ steps.buildozer.outputs.filename }}


  android-release:
    name: Android (release)
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'buildozer-release')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: ${{ job.android-debug.buildozer.workdir }}
          buildozer_version: ${{ job.android-debug.buildozer.buildozer_version }}
          command: buildozer android release

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: ${{ steps.buildozer.outputs.filename }}

