name: Buildozer
on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: launcher
          # #buildozer_version: stable
          # buildozer_version: 1.2.0
          # #command: buildozer android debug
          # command: buildozer android release

          # for aab (android bundle)
          buildozer_version: feat/aab-support
          
          
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
